# Generated by Django 3.2.13 on 2023-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0002_alter_article_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='progress',
            field=models.BooleanField(default=True, verbose_name='progreso'),
        ),
    ]
