# Generated by Django 4.1.5 on 2023-02-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0004_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='nombre')),
                ('description', models.TextField(max_length=250, verbose_name='descipcion')),
                ('offert', models.IntegerField(verbose_name='oferta')),
                ('value', models.IntegerField(verbose_name='valor')),
                ('image', models.ImageField(upload_to='servicios', verbose_name='imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telephone',
            field=models.IntegerField(),
        ),
    ]
