# Generated by Django 4.1.5 on 2023-02-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0005_service_alter_perfil_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='null', upload_to='servicios', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='service',
            name='offert',
            field=models.IntegerField(default='null', verbose_name='oferta'),
        ),
    ]
