# Generated by Django 4.1.5 on 2023-02-01 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0006_alter_service_image_alter_service_offert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='offert',
        ),
        migrations.RemoveField(
            model_name='service',
            name='value',
        ),
    ]
