# Generated by Django 4.1.5 on 2023-02-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0008_service_subservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subservices',
            field=models.TextField(max_length=250, verbose_name='sub-servicios'),
        ),
    ]
