# Generated by Django 4.1.5 on 2023-02-01 19:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0009_alter_service_subservices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subservices',
            field=ckeditor.fields.RichTextField(verbose_name='sub-servicios'),
        ),
    ]
