# Generated by Django 4.1.5 on 2023-02-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0010_alter_service_subservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='nombre')),
                ('lastName', models.CharField(max_length=30, verbose_name='apellido')),
                ('email', models.EmailField(max_length=50, verbose_name='correo')),
                ('phone', models.CharField(max_length=12, verbose_name='telefono')),
                ('description', models.TextField(max_length=255, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
            ],
        ),
    ]
