# Generated by Django 4.1.5 on 2023-02-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0011_contacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
