# Generated by Django 4.1.5 on 2023-02-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0012_rename_contacts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='slug',
            field=models.CharField(default='null', max_length=200, verbose_name='Enlace'),
        ),
    ]
