# Generated by Django 4.1.5 on 2023-02-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0013_proyect_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='slug',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
    ]
