# Generated by Django 4.1.5 on 2023-02-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0016_alter_article_public'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='surname',
            new_name='lastname',
        ),
    ]
