# Generated by Django 4.1.5 on 2023-02-10 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0017_rename_surname_perfil_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='social',
            field=models.URLField(blank=True, null=True),
        ),
    ]
