# Generated by Django 4.1.5 on 2023-02-11 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0018_perfil_social'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='social',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='perfil',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='whatsapp',
            field=models.URLField(blank=True, null=True),
        ),
    ]
