# Generated by Django 4.1.5 on 2023-02-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0019_rename_social_perfil_facebook_perfil_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='null', verbose_name='descripcion'),
        ),
    ]
