# Generated by Django 4.1.5 on 2023-02-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0020_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(verbose_name='descripcion'),
        ),
    ]
