# Generated by Django 4.1.5 on 2023-02-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0023_alter_article_description_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='description',
            field=models.TextField(max_length=200, verbose_name='descripcion'),
        ),
    ]
