# Generated by Django 4.1.5 on 2023-02-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0024_alter_curso_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portafolio.curso', verbose_name='cursos'),
        ),
    ]
