# Generated by Django 4.1.5 on 2023-02-20 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0026_clases'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clases',
            options={'verbose_name': 'Clase', 'verbose_name_plural': 'Clases'},
        ),
        migrations.AlterModelOptions(
            name='contenido',
            options={'verbose_name': 'Contenido', 'verbose_name_plural': 'Contenidos'},
        ),
    ]
