# Generated by Django 4.1.5 on 2023-02-20 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0027_alter_clases_options_alter_contenido_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clases',
            name='content',
        ),
        migrations.AddField(
            model_name='contenido',
            name='clase',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='portafolio.clases', verbose_name='Clase'),
        ),
    ]
