# Generated by Django 4.1.5 on 2023-02-20 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0028_remove_clases_content_contenido_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenido',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portafolio.clases', verbose_name='Clase'),
        ),
    ]
