# Generated by Django 4.1.5 on 2023-02-20 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0029_alter_contenido_clase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='clase',
        ),
        migrations.AddField(
            model_name='clases',
            name='content',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='portafolio.contenido', verbose_name='contenido'),
        ),
    ]
