# Generated by Django 4.1.5 on 2023-02-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0031_alter_clases_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portafolio.curso', verbose_name='curso'),
        ),
    ]
