# Generated by Django 4.1.5 on 2023-02-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0032_clases_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clases',
            old_name='content',
            new_name='contenido',
        ),
    ]
