# Generated by Django 4.1.5 on 2023-02-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0033_rename_content_clases_contenido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clases',
            name='title',
        ),
        migrations.AddField(
            model_name='clases',
            name='title_class',
            field=models.CharField(default=1, max_length=200, verbose_name='titulo clase'),
        ),
    ]
