# Generated by Django 4.1.5 on 2023-02-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0034_remove_clases_title_clases_title_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='title_class',
            field=models.CharField(max_length=200, verbose_name='titulo clase'),
        ),
    ]
