# Generated by Django 4.1.5 on 2023-02-22 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0038_alter_clases_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.curso', verbose_name='curso'),
        ),
    ]
