# Generated by Django 4.1.5 on 2023-02-24 16:42

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0040_perfil_diplomas'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='video',
            field=models.URLField(blank=True, default='null', max_length=400),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='diplomas',
            field=ckeditor.fields.RichTextField(verbose_name='Diplomas'),
        ),
    ]
