# Generated by Django 4.1.5 on 2023-02-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0041_contenido_video_alter_perfil_diplomas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido',
            name='video',
        ),
        migrations.AddField(
            model_name='curso',
            name='video',
            field=models.URLField(blank=True, default='null', max_length=400),
        ),
    ]
