# Generated by Django 4.1.5 on 2023-02-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0042_remove_contenido_video_curso_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='video',
            field=models.TextField(default='null', max_length=400),
        ),
    ]
