# Generated by Django 4.1.5 on 2023-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0044_remove_clases_url_clases_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='slug',
            field=models.URLField(blank=True, default=True, null=True, verbose_name='Enlace'),
        ),
    ]
