# Generated by Django 4.1.5 on 2023-03-19 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0045_alter_proyect_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.contenido', verbose_name='contenido'),
        ),
        migrations.AlterField(
            model_name='contenido',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.curso', verbose_name='cursos'),
        ),
    ]
