# Generated by Django 4.1.5 on 2023-04-02 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0049_remove_commenttocomment_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commenttocomment',
            name='comment',
        ),
        migrations.AddField(
            model_name='commenttocomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portafolio.comment', verbose_name='comentario'),
        ),
    ]
