# Generated by Django 4.1.5 on 2023-04-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0050_remove_commenttocomment_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='meta_title',
            field=models.CharField(max_length=100, null=True, verbose_name='titulo-pestaña'),
        ),
    ]
