# Generated by Django 4.1.5 on 2023-04-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0051_page_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='page',
            name='metaTitle',
            field=models.CharField(max_length=100, null=True, verbose_name='titulo-meta'),
        ),
    ]
