# Generated by Django 4.1.5 on 2023-05-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0053_valorationcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorationcourse',
            name='valoracion',
            field=models.CharField(max_length=3, verbose_name='valoracion'),
        ),
    ]
