# Generated by Django 4.1.5 on 2023-05-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0054_alter_valorationcourse_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='aprenderas',
            field=models.TextField(max_length=400, null=True, verbose_name='aprenderas'),
        ),
    ]
