# Generated by Django 4.1.5 on 2023-05-11 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0059_remove_curso_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='description',
            field=models.CharField(max_length=400, verbose_name='Descripcion'),
        ),
    ]
