# Generated by Django 4.1.5 on 2023-05-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0060_alter_perfil_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='diplomas',
            field=models.TextField(verbose_name='Diplomas'),
        ),
    ]
