# Generated by Django 4.1.5 on 2023-05-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0061_alter_perfil_description_alter_perfil_diplomas'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='category',
            field=models.ManyToManyField(to='portafolio.category', verbose_name='Categoria'),
        ),
    ]
