# Generated by Django 4.1.5 on 2023-05-12 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0062_curso_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='category',
        ),
        migrations.AddField(
            model_name='curso',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portafolio.category', verbose_name='Categoria'),
        ),
    ]
