# Generated by Django 4.1.5 on 2023-05-12 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0063_remove_curso_category_curso_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portafolio.perfil', verbose_name='perfil'),
        ),
    ]
