# Generated by Django 4.1.5 on 2023-05-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0064_alter_curso_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='level',
            field=models.CharField(default='Silver', max_length=10, verbose_name='nivel'),
        ),
    ]
