# Generated by Django 4.1.5 on 2023-05-15 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0065_perfil_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
                ('classVideo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.clases', verbose_name='clase')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.perfil', verbose_name='usuario')),
            ],
        ),
    ]
