# Generated by Django 4.1.5 on 2023-05-18 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0066_commentclase'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentclase',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portafolio.perfil', verbose_name='perfil'),
        ),
    ]
