# Generated by Django 4.1.5 on 2023-05-15 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0066_commentvideo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentVideo',
            new_name='CommentClase',
        ),
    ]
