# Generated by Django 4.1.5 on 2023-05-18 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0067_commentclase_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentclase',
            name='user',
        ),
    ]
