# Generated by Django 4.1.5 on 2023-05-19 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portafolio', '0068_remove_commentclase_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResComClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portafolio.commentclase', verbose_name='comentario')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portafolio.perfil', verbose_name='usuario')),
            ],
        ),
    ]
