# Generated by Django 4.1.5 on 2023-05-24 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portafolio', '0070_mycourse_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='curso',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portafolio.curso', verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
